services:
  bartek0x1001:
    build: .
    container_name: bartek0x1001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null
