services:
  bartek0x1001:
    build: .
    container_name: bartek0x1001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1
      - TERM=${TERM:-xterm-256color}
    command: tail -f /dev/null
